included:
  - Selkie
  - SelkieTunnelExtension
  - SelkieTests
  - Shared
excluded:
  - Selkie.xcodeproj
reporter: xcode
strict: true
file_length:
  warning: 500
  error: 500
type_body_length:
  warning: 400
  error: 400
function_body_length:
  warning: 100
  error: 100
